apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  selector:
    app: django-messaging
    version: blue  # Switch to 'green' for traffic migration
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
